# Generated by Django 3.2.3 on 2023-10-20 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrecipes',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления (в минутах)'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(help_text='Название рецепта', max_length=200, validators=[django.core.validators.RegexValidator(message='Название рецепта состоит только из букв', regex='^[[:alpha:]]+\\Z')], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(help_text='Название тега', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Тег состоит только из букв', regex='^[[:alpha:]]+\\Z')], verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(max_length=32),
        ),
    ]
